//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECres.Datos.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TECresEntities : DbContext
    {
        public TECresEntities()
            : base("name=TECresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Anuncio> Anuncio { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Foto_Secundaria> Foto_Secundaria { get; set; }
        public virtual DbSet<Gestion_vendedores> Gestion_vendedores { get; set; }
        public virtual DbSet<Interesado> Interesado { get; set; }
        public virtual DbSet<Mensaje> Mensaje { get; set; }
        public virtual DbSet<Nacionalidad> Nacionalidad { get; set; }
        public virtual DbSet<Ocupacion> Ocupacion { get; set; }
        public virtual DbSet<Perfil_cliente> Perfil_cliente { get; set; }
        public virtual DbSet<Propiedad> Propiedad { get; set; }
        public virtual DbSet<Publico> Publico { get; set; }
        public virtual DbSet<Tipo_anuncio> Tipo_anuncio { get; set; }
        public virtual DbSet<Tipo_Inmueble> Tipo_Inmueble { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
    
        public virtual ObjectResult<Filtros_Result> Filtros(Nullable<int> habitaciones, Nullable<int> precioMin, Nullable<int> precioMax, Nullable<int> ubicacion)
        {
            var habitacionesParameter = habitaciones.HasValue ?
                new ObjectParameter("Habitaciones", habitaciones) :
                new ObjectParameter("Habitaciones", typeof(int));
    
            var precioMinParameter = precioMin.HasValue ?
                new ObjectParameter("PrecioMin", precioMin) :
                new ObjectParameter("PrecioMin", typeof(int));
    
            var precioMaxParameter = precioMax.HasValue ?
                new ObjectParameter("PrecioMax", precioMax) :
                new ObjectParameter("PrecioMax", typeof(int));
    
            var ubicacionParameter = ubicacion.HasValue ?
                new ObjectParameter("Ubicacion", ubicacion) :
                new ObjectParameter("Ubicacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Filtros_Result>("Filtros", habitacionesParameter, precioMinParameter, precioMaxParameter, ubicacionParameter);
        }
    
        public virtual ObjectResult<string> ObtenerCantones(string provincia)
        {
            var provinciaParameter = provincia != null ?
                new ObjectParameter("Provincia", provincia) :
                new ObjectParameter("Provincia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ObtenerCantones", provinciaParameter);
        }
    
        public virtual ObjectResult<string> ObtenerDistritos(string provincia, string canton)
        {
            var provinciaParameter = provincia != null ?
                new ObjectParameter("Provincia", provincia) :
                new ObjectParameter("Provincia", typeof(string));
    
            var cantonParameter = canton != null ?
                new ObjectParameter("Canton", canton) :
                new ObjectParameter("Canton", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ObtenerDistritos", provinciaParameter, cantonParameter);
        }
    
        public virtual ObjectResult<Fotos_Secundarias_Result> Fotos_Secundarias(Nullable<int> id_propiedad)
        {
            var id_propiedadParameter = id_propiedad.HasValue ?
                new ObjectParameter("id_propiedad", id_propiedad) :
                new ObjectParameter("id_propiedad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fotos_Secundarias_Result>("Fotos_Secundarias", id_propiedadParameter);
        }
    
        public virtual ObjectResult<Anunciosporaprobar_Result> Anunciosporaprobar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Anunciosporaprobar_Result>("Anunciosporaprobar");
        }
    }
}
