//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECres.Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propiedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propiedad()
        {
            this.Foto_Secundaria = new HashSet<Foto_Secundaria>();
        }
    
        public double tamano_construccion { get; set; }
        public double tamano_terreno { get; set; }
        public int niveles { get; set; }
        public string tipo_piso { get; set; }
        public bool piscina { get; set; }
        public bool gimnasio { get; set; }
        public int cantidad_banos { get; set; }
        public int cant_habitaciones { get; set; }
        public int espacios_parqueo { get; set; }
        public bool parqueo_visitas { get; set; }
        public string titulo { get; set; }
        public int ubicacion { get; set; }
        public int id_dueno { get; set; }
        public string inmueble { get; set; }
        public int id_propiedad { get; set; }
        public string foto_principal { get; set; }
    
        public virtual Anuncio Anuncio { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foto_Secundaria> Foto_Secundaria { get; set; }
        public virtual Tipo_Inmueble Tipo_Inmueble { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
    }
}
